import type { Metadata } from "next";
import { PagePlaceholder } from "@/components/shared/page-placeholder";

export const metadata: Metadata = { title: "Conversation" };

/**
 * `params` is a Promise in Next 16 and `PageProps` is generated by
 * `next typegen`, which gives the route's own parameter names their real types.
 */
export default async function ConversationThreadPage({
  params,
}: PageProps<"/conversations/[conversationId]">) {
  const { conversationId } = await params;

  return (
    <PagePlaceholder
      title="Conversation"
      description={`Message thread for conversation ${conversationId}. The identifier is not validated or authorized yet.`}
      implementedBy="Task 4.2"
    />
  );
}
